[package]
name = "radiorecord-tui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crossterm = { version = "0.20", features = [ "serde" ] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
tui = { version = "0.16", default-features = false, features = ['crossterm', 'serde'] }
thiserror = "1.0"

rodio = { git ="https://github.com/RustAudio/rodio",default-features = false, features = ['symphonia-aac']  }
curl = "0.4.38"

asciifyer= {version="0.1.1" }

[[bin]]
bench = false
path = "src/main.rs"
name = "rrt"